### ISSUE TITLE
Maximum call stack size exceeded when querying locally with 150,000 entity manager

### ISSUE THREAD

**Issue by travisperson** [Breeze/breeze.js#105]
The actual number may be different for different users, I can get it to hit around 135,000 in this little demo. 

Example: http://jsfiddle.net/328y8xmd/12

It doesn't appear to matter how many you try to extract. Just the fact of having 150,000 records causes things to break down.

**Comment by jtraband** [comment]
If you are using the default `modelLibrary`, then breeze creates `knockout` objects which are very heavy.  Try using the `backingStore` modelLibrary instead; each object will then be much, much smaller and you can create many more of them.

**Comment by travisperson** [comment]
Are you referring to setting the following?

```
breeze.config.initializeAdapterInstance("modelLibrary", "backingStore", true);
```

**Comment by travisperson** [comment]
That is not really the issue here though. The issue is this line:

```
 result.push.apply(result, group._entities.filter(newFilterFunc));
```

When the group has all 150,000 entities it's like calling `results.push(1,2,3,4,5,6,7,...,149998, 149999,150000)`

**Comment by travisperson** [comment]
Different ways to append to arrays and their perfs: http://jsperf.com/array-prototype-push-apply-vs-concat/75

It would appear using concat is the best option.

**Comment by travisperson** [comment]
I can submit a PR for a fix to this if you think it's an actual issue that should be fixed. Having 150,000 entities in a single group may not be ideal. If so, can you provide insight?

**Comment by steveschmitt** [comment]
Yes, if you have a fix that works for you, please submit a pull request.

Having 150,000 entities is not ideal - can't you filter them on the server?  But, if that's what your application needs, that's your business.  Breeze should not be the limiting factor.

**Comment by wardbell** [comment]
Don't bother. I've made the change and tested that it works (w/ DocCode). 

Does it perform better under load? That is something I WOULD like @travisperson  to try.

Here is my replacement code, beginning on line #13577 of breeze.debug.js

```
    var result = [];
    // TODO: mapMany
    groups.forEach(function (group) {
        var entities = group._entities.filter(newFilterFunc);
        if (entities.length) {
            result = result.length ? result.concat(entities) : entities;
        }
    });
```
@travisperson - Would you mind pasting that into your breeze.debug.js and give it a go?

**Comment by travisperson** [comment]
:+1: Works like a charm, thanks! 

The performance differences at low numbers is almost negligible. Both performed around ~25ms for 120,000 entities. This one does scale though, easily hitting 750,000 entities and query against them all.

**Comment by wardbell** [comment]
I'd say we're done then.
