### ISSUE TITLE
cannot find module breeze with browserify

### ISSUE THREAD

**Issue by JCherryhomes** [Breeze/breeze.js#110]
I am attempting to load breeze using browserify. I used npm to install the breeze-client library. If I run browserify without including breeze everything runs fine, but when I include breeze I get the following error:

```
Error: Cannot find module 'breeze' from 'C:\...\node_modules\breeze-client'
```

i've tried doing the require every way I can think of

```
require("breeze-client");
require("breeze-client/breeze.debug");
require("breeze-client/breeze.debug.js");
require("../node_modules/breeze-client");
etc...
```

Any ideas?

I also opened a stackoverflow question: [stackoverflow](https://stackoverflow.com/questions/32289895/cannot-find-module-breeze-with-browserify)

**Comment by JCherryhomes** [comment]
breeze-client version 1.5.5

**Comment by nojaf** [comment]
Having the same problem!

**Comment by wardbell** [comment]
What npm package did you install?  Note that the `breezejs` package is deprecated. Is this a problem with the `breeze-client` package (v.1.5.5)?

If so, please tell me how to fix it. I could figure it out but this is an open source project and I don't use browserify personally. Your contributions are helpful and welcome.

**Comment by nojaf** [comment]
Well in the breeze source code, if you do a ctrl-f on require("breeze") you will find some matches. But the package name is "breeze-client".

The steps to reproduce are:

- Create a new empty folder and go ```npm install breeze-client```
- create a index.js file with
```
var breeze = require("breeze-client")
```
- download browserify ```npm install browserify -g```
- run ```browserify index.js > bundle.js```

This will complain about cannot find package "breeze"

If you change require("breeze") to require("breeze-client") the browserify command will execute ok.

**Comment by mattrandle** [comment]
Yes i can confirm the same behavior - the adapters that are bundled into the breeze.debug.js include a require("breeze") statement which wont resolve because the npm package is named breeze-client.

**Comment by nojaf** [comment]
Created https://github.com/Breeze/breeze.js/pull/112
The only thing you might run into is that at runtime Q will not be defined.

Workaround:
```js
var breeze = require("breeze-client");
var q = require("q");
breeze.config.setQ(q);
```

And you might have the same problem for jQuery, I'm not having this issue cause I've written a custom ajax adapter.

**Comment by JCherryhomes** [comment]
thanks @nojaf, updating all of the requires to use "breeze-client" got it working for me

**Comment by steveschmitt** [comment]
I merged in dimlock's change a while back.  Did that fix this problem?

**Comment by JCherryhomes** [comment]
didn't realize this was still open, yes that fixed it
