### ISSUE TITLE
Bad URL in docs

### ISSUE THREAD

**Issue by MB34** [Breeze/breeze.js#120]
On this page:
http://breeze.github.io/doc-net/odata

The link to Brian Noyes blog post on consuming OData services with Breeze:
http://briannoyes.net/2013/02/16/ConsumingAnASPNETWebAPIODataServiceWithBreeze.aspx

Needs to be changed to:
http://briannoyes.net/consuming-an-asp-net-web-api-odata-service-with-breeze/

**Comment by Josh4gitaboutit** [comment]
Corrected link and successfully tested. Thank you very much for the notification and providing the new  target URL!!
