### ISSUE TITLE
npm claims version 1.5.5, but last release is only 1.5.4

### ISSUE THREAD

**Issue by nmschulte-aviture** [Breeze/breeze.js#130]
What's going on here?  I also see that there are some stale pull requests with bugfixes, etc; am I missing something?  Where did v1.5.5 come from?

**Comment by steveschmitt** [comment]
Yes, we need to sync up the releases.

**Comment by steveschmitt** [comment]
Now updated to 1.5.6 to fix the version mismatch.  Sorry about that.
