### ISSUE TITLE
Unable to add child entities on navigation property

### ISSUE THREAD

**Issue by danielgerlag** [Breeze/breeze.js#140]
I am unable to add child entities on navigation property of an existing entity.
Using this metadata (attached), create a "Brokerage" and then try to push a "BrokerageBranch" onto the "Branches" navigation property, does nothing.

[metadata.txt](https://github.com/Breeze/breeze.js/files/188850/metadata.txt)

**Comment by steveschmitt** [comment]
If you retrieve a Brokerage and its associated BrokerageBranches from the server, are they related correctly on the client?

**Comment by danielgerlag** [comment]
Yes, but they are not attached to the navigation collection.  Almost like the collection property ignores all adds

**Comment by danielgerlag** [comment]
This is actually an issue with incorrect metadata being generated by ASP.NET WebAPI OData.
