### ISSUE TITLE
Please tag the 1.5.5 release

### ISSUE THREAD

**Issue by josundt** [Breeze/breeze.js#141]
I am not able to install latest breeze-client using bower. Latest available version is 1.5.4.
Please tag the release so that I can install latest version.

**Comment by josundt** [comment]
I also noticed the same that was already reported in issue #130; npm package breeze.client@1.5.5 contains the 1.5.4 script.
Currently, only NuGet installs the latest release successfully. Please fix!

**Comment by steveschmitt** [comment]
Now updated (and tagged) to 1.5.6 to fix the version mismatch.  Sorry about that.
