### ISSUE TITLE
Module names issues

### ISSUE THREAD

**Issue by blazkovicz** [Breeze/breeze.js#142]
I am really curious why breeze requires modules (and even self) with some random names that are not equal to official names stated in bower.json files for modules: "jQuery" instead of "jquery", "ko" instead of "knockout" and "breeze" instead of "breeze-client"?

breeze module name in bower is 'breeze-client', so why inside own code it requires self with name 'breeze'?

If all third party libraries will use random names for known modules all will have a hell of a lot to do to combine the app together.

**Comment by steveschmitt** [comment]
With 1.5.6, we now use "breeze-client" to require the module.
"ko" and "jQuery" are the names that those libraries use in the global namespace, and those predate bower.  We need to use separate names for module scenarios.

**Comment by blazkovicz** [comment]
Please use bower names for modules (or both old and new names).

**Comment by steveschmitt** [comment]
Fixed in recent commit; will be in next release.
Thanks for pointing this out.
