### ISSUE TITLE
bower.json parameter 'name'

### ISSUE THREAD

**Issue by blazkovicz** [Breeze/breeze.js#143]
Please, set parameter "name" in bower.json to string not to array since it contains only one path.
This will help webpack to find breeze code file automatically without alias.

**Comment by steveschmitt** [comment]
The "name" property was already a string.  I've also changed the "main" property to a string.  Let me know if that helps.

**Comment by blazkovicz** [comment]
Ups, I was talking about main, just misspelled (twice :-)). Thanks a lot!
