### ISSUE TITLE
With iso date string save

### ISSUE THREAD

**Issue by Zuzon** [Breeze/breeze.js#145]
If i try save '2014-11-02T18:00:00' as string, breeze automatically converts it to '11/02/2014 18:00:00'

property datatype is String, and isDate is false.

How can i solve this problem?

**Comment by steveschmitt** [comment]
Are you using .NET (ContextProvider) on the server?  This seems to happen when the JSON deserializer 
assigns the values to the entity on the server.  It's happening in [ContextProvider.cs](https://github.com/Breeze/breeze.server.net/blob/master/Breeze.ContextProvider/ContextProvider.cs), line 231.

I'm not sure of the best way to fix this.

**Comment by Zuzon** [comment]
No, it happens on the client before sending to the server

**Comment by steveschmitt** [comment]
Hmm, I can't reproduce that.  When I look at the network traffic (using Chrome's Developer Tools), I see '2014-11-02T18:00:00' in the request payload, but '11/02/2014 18:00:00' in the response.

**Comment by Zuzon** [comment]
Ow, you are right! It's a my fail. apologies.
