### ISSUE TITLE
Add option to use withParameters with Json-style queries

### ISSUE THREAD

**Issue by rastographics** [Breeze/breeze.js#147]
Can we add the `withParameters` property to the Json-query syntax? Loving json for all my queries but  have to use the other style for queries that hit a named endpoint.

**Comment by steveschmitt** [comment]
It's already there.  Just add another key called "parameters" to your query object:

    "parameters":{"companyName":"C"}

**Comment by rastographics** [comment]
Awesome. Submitted PR to add this to the docs example. Thanks.
https://github.com/Breeze/breeze.github.io/pull/8
