### ISSUE TITLE
Requests for $metadata has Accept: application/json;odata.metadata=full

### ISSUE THREAD

**Issue by prilling** [Breeze/breeze.js#148]
Response from $metadata can only be in XML, but the Breeze client (breeze.dataService.odata.js) is asking for json.  This is wrong and causes the server to respond with 406.

Here is what the spec says about Accept: "If no Accept header field is present, then it is assumed that the client accepts all media types. If an Accept header field is present, and if the server cannot send a response which is acceptable according to the combined Accept field value, then the server SHOULD send a 406 (not acceptable) response." -- https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by steveschmitt** [comment]
Good point.  I changed it to "application/*; odata.metadata=full".  Fix will be in v1.5.11

Thanks for pointing this out.
