### ISSUE TITLE
FilterQueryOp.in missing?

### ISSUE THREAD

**Issue by TheHandsomeCoder** [Breeze/breeze.js#149]
Hi I'm currently writing my a set of adapters for Breeze so I can connect to my JSON-API and I notice in the ODATA uribuilder there is a mention of the "in" operator which allows to specify a list.

Looking through the docs the only reference I can find to this is in the JSON-Query. Should this be referenced as part of the FilterQueryOp Enum or am I just missing part of the documentation?

**Comment by steveschmitt** [comment]
You are right!  I just added it.  Thanks!
