### ISSUE TITLE
Invalid dates and breaking change in Breeze.js 1.5.5

### ISSUE THREAD

**Issue by rwhepburn** [Breeze/breeze.js#151]
Hey there,

After upgrading to Breeze 1.5.5, I'm experiencing the following exception related to the changes made to the DateTimeOffset normalize functionality:

```logger.ts:75 An unexpected error happened (Uncaught TypeError: value.getTime is not a function [https://localhost:44300/scripts/breeze.debug.js line: 5829, col: 56])```

I have a scenario where I'm binding an entity date property to a DateTimePicker (I'm using Knockout). Using the DateTimePicker control, it's possible for the user to manually enter an invalid date (e.g. "dsasda") into the control. In order to display a broken validation rule indicator, I need the breeze validator to run so the underlying breeze property is updated to the invalid value.

However, the changes to DataType.DateTimeOffset `normalize: function(value) { return value && value.getTime(); }` (line 5832 in breeze.debug.js) now causes an exception to be thrown since it assumes value is a `Date` object, which may not be true in the case where it's invalid. 

This seems to be a breaking change over how this was handled in 1.5.4 as it's not coercing the dates in the same manner.

Here's the code from 1.5.4:
```
  DataType.DateTimeOffset = DataType.addSymbol({
  defaultValue: new Date(1900, 0, 1), isDate: true,
  parse: coerceToDate,
  fmtOData: fmtDateTimeOffset,
  getNext: getNextDateTime
  });
```

And the in 1.5.5:
```
  DataType.DateTimeOffset = DataType.addSymbol({
    defaultValue: new Date(1900, 0, 1),
    isDate: true,
    parse: coerceToDate,
    parseRawValue: parseRawDate,

    normalize: function(value) { return value && value.getTime(); /* BOOM! */ }, // dates don't perform equality comparisons properly
    fmtOData: fmtDateTimeOffset,
    getNext: getNextDateTime,
    getConcurrencyValue: getConcurrencyDateTime
  });
```

**Comment by rwhepburn** [comment]
Further to this, I discovered I was accidentally setting the breeze entity's property to a moment() date object. While this was clearly wrong, breeze strangely did not complain about this in 1.5.4. 

Even after fixing this by attempting to set the entity's date property to the invalid string value (e.g. "dsasda"), the same exception would occur since the `normalize` function always assumes a `Date` object now and not a string.

As a workaround, I'm now setting the entity's date property to `new Date('dsasda')`. This creates a new invalid `Date` object and seems to fix things for me.

I think it would make sense to apply the same logic to the `normalize` function if the date received is not valid. 

Thanks

**Comment by steveschmitt** [comment]
Thanks for pointing this out.  I'll take a look.

**Comment by steveschmitt** [comment]
I put in a fix for this.  It will be in the 1.5.7 release.  Thanks again for finding this.
