### ISSUE TITLE
OData request headers

### ISSUE THREAD

**Issue by morious** [Breeze/breeze.js#154]
Hi,
I am trying to control the headers of an OData request from breeze.
I came across these line in breeze js code:
 OData.read({
          requestUri: url,
          // headers: { "Accept": "application/json"}
          headers: { Accept: 'application/json;odata.metadata=full' }
        },

IT would make sense for the OData adapter headers to be taken into consideration, ex: merged into this hard coded headers obj.
Is it a fair statement or am i missing something?

Thanks!

**Comment by steveschmitt** [comment]
Yes, that makes perfect sense.  I just checked in a fix, which will be in the 1.5.8 release.

**Comment by morious** [comment]
This is great Steve. Thx!
