### ISSUE TITLE
$batch request broken because headers are accumulated forever

### ISSUE THREAD

**Issue by kferstl** [Breeze/breeze.js#157]
**bug in this commit**
https://github.com/nifdex/breeze.js/commit/cf2175c0e7747ab422d0aaa37fb8fd82f445aa8e

**solution**
pullrequest: https://github.com/Breeze/breeze.js/pull/158
open
`breeze.dataService.odata.js`
search for
`headers: this.headers`
replace with 
`headers: __extend({}, this.headers)`
(multiple times)

**description**
datajs library fills this.headers with headers that stay forever. Problem occures when the $batch request sets the "Content-Type: multipart/mixed; boundary=changeset_xxxxx" header, xxx stays forever and is not overwritten by datajs. Therefor the server ignores all $batch request after the first one.

**feelings**
super annoying bug :/

**Comment by steveschmitt** [comment]
Thanks for pointing this out.  Fixed in 1.5.11 release.
