### ISSUE TITLE
Rename require('breeze') to require('breeze-client') - redux for AMD

### ISSUE THREAD

**Issue by dwarry** [Breeze/breeze.js#161]
#118 saw this change for CommonJS modules, but left the AMD versions of the adapters using the old name. I've been trying to get breeze to work with the Aurelia CLI and bundler, which is currently using AMD modules, and this confuses it!

Is there any reason the two module definitions couldn't be brought into line?

**Comment by marcelgood** [comment]
No reason. It just didn't get changed. I checked in a fix to have the AMD module name be consistent with the CommonJS/NodeJS module name. Good catch.

**Comment by marcelgood** [comment]
This fix is now in the 1.5.11 npm package.
