### ISSUE TITLE
Recommended way to test javascript breeze entities

### ISSUE THREAD

**Issue by rastographics** [Breeze/breeze.js#167]
I'm using breeze with typescript and have your [wonderful tooling](https://github.com/Breeze/breeze.tooling) in place to generate all my typescript entities.

I now need to test the functions that I have added to these breeze entities in typescript.

Is it a bad approach to have an npm script that would run launch breeze in node and pull down entities from my dev server, and save those entities as json, so they could then be loaded into breeze for my tests and I can be testing my entities functions on actual entities from the database (without hitting the database during the testing).

Is there a better approach?  

Sorry if I sound ignorant, I've been using breeze for a year but I'm new to unit testing and seeing how awesome it is, I really want to implement testing for my entity functions.

**Comment by marcelgood** [comment]
Yes, that would be a possible approach, but perhaps overkill. You can also simply new up a bunch of your entities, initialize them with test data and then test your functions.

**Comment by rastographics** [comment]
Getting frustrated re-creating my testable entities from hand (they get very complicated). 
Really surprised no one has written an ajaxAdapter for node yet (to generate a json file for testable entities). Taking it to [stackoverflow ](http://stackoverflow.com/questions/40054710/run-breeze-entity-manager-in-node)to see if anyone has tried this recently.

**Comment by steveschmitt** [comment]
You can load your entities into Breeze in the browser, then [entityManager.exportEntities](http://breeze.github.io/doc-js/api-docs/classes/EntityManager.html#method_exportEntities) to serialize all the entities to a big string.  Then you can save the string, and then `entityManager.importEntities` to re-populate your entityManager for testing.
