### ISSUE TITLE
Do you recommend using Breeze with Angular2?

### ISSUE THREAD

**Issue by rodneyjoyce** [Breeze/breeze.js#173]
Hi All,

Firstly, thanks for all the hardwork on Breeze, I have used it on a few Angular1 projects and it has saved a fair bit of time.

Out of interest, do you recommend using BreezeJS with Angular2? I have it working, however I have noticed there is not a lot of activity for it and I am considering scrapping it and writing data services the pure Angular2 way. I would love to hear from Ward or some other of the project sponsors if they personally still recommend using Breeze for Angular2 projects? (I watched some Angular2 videos on Pluralsight and it was not mentioned (obviously because of the desire to focus on ng2 solely) - however I would appreciate any advice on this matter.

For example, one of the benefits of not using it might be strong typing of the POCO objects on the client (even if they are hand-coded). I am not sure how to do this with Breeze and Typescript.

**Comment by marcelgood** [comment]
Yes, we definitely recommend using Breeze with Angular 2. We've done several projects ourselves. There is no reason not to use it for a project for which you would have used it with Angular 1. We have written some tools that allow you to generate the Entity TypeScript classes from the metadata, so you have strong typing for your entities and can easily extend them. The next version of Breeze will be written TypeScript for a more first class experience. An Alpha/Beta release should be coming soon. However, the current version is all you need to use it with Angular 2. We've also written a bridge that configures Breeze properly for Angular 2 and we have a reference application that demonstrates real world scenarios. Here are a couple of links that should get you started.

Tooling to generate TypeScript entity classes:
https://github.com/Breeze/breeze.tooling

Breeze-Angular 2 bridge:
https://github.com/Breeze/breeze.bridge.angular2

Angular 2/Breeze reference application:
https://github.com/Breeze/temphire.angular2

**Comment by rodneyjoyce** [comment]
Thanks for the encouraging comments - I'll spend some time digging into it. Looking forward to the Typescript rewrite too!

**Comment by rodneyjoyce** [comment]
Btw - one of the areas I am battling to get my head around is how to add authentication to the headers.

I am using Auth0 which has it's own AuthHTTP implementation of the core HTTP class - however I cannot use it as I am using Breeze. 

Do you have any examples with Breeze and Angular2 (it was easy with interceptors in ng1) where you add tokens to headers and do authentication?

Thanks

**Comment by rodneyjoyce** [comment]
FYI, this is what I have so far in the constructor of my DataService which inits Breeze, however the token is loaded once on startup - I need to somehow attach it for every request (in case users log in/out or token expires etc):
```

        // get the current default Breeze AJAX adapter
        var ajaxAdapter: any = config.getAdapterInstance('ajax');
        console.log('ajaxAdapter', ajaxAdapter);

        // set fixed headers
        var token = localStorage.getItem('id_token');
        console.log(token);
        if (token) {
            if (tokenNotExpired()) // Check if there's an unexpired JWT - It searches for an item in localStorage with key == 'id_token'
            {
                ajaxAdapter.defaultSettings = {
                    headers: {
                        "Authorization": "Bearer " + token
                    }
                }
            }
        }
```

**Comment by wardbell** [comment]
Assuming that you know how to configure `AuthHTTP` , I'm taking a guess but I'm pretty sure that you can arrange for Breeze to use `AuthHTTP` without any other trickery.

I'm looking at the [instructions for registering the `AuthHTTP` provider](https://github.com/auth0/angular2-jwt/blob/master/README.md) which look like this:
```
import { NgModule } from '@angular/core';
import { AUTH_PROVIDERS } from 'angular2-jwt';

@NgModule({
  ...
  providers: [
    AUTH_PROVIDERS
  ],
  ...
})
```
I think`AUTHPROVIDERS` registers `AuthHTTP` under the `http` token. If so, I'll bet that Breeze will inject `AuthHTTP` into itself as long as your root `AppModule` imports the Breeze bridge module _after_ registering the auth0 providers.

To get the sequence right you might  try something like this:
```
import { NgModule } from '@angular/core';
import { AUTH_PROVIDERS } from 'angular2-jwt';
import { BreezeBridgeAngular2Module } from 'breeze-bridge-angular2';

@NgModule({
  providers: [ AUTH_PROVIDERS ]
})
class Auth0Module { }

@NgModule({
  imports: [
    BrowserModule,
    Auth0Module,
    BreezeBridgeAngular2Module,
    ...
  ],
  ...
  ],
  ...
})
export class AppModule { }
```
This sequence ensures that Auth0 provides `http` (within the `Auth0Module`) _before_ the `BreezeBridgeAngular2Module`  asks for it to be injected ... which it does in the constructor of the `BreezeBridgeAngular2Module` (see [constructor](https://github.com/Breeze/breeze.bridge.angular2/blob/master/src/breeze-bridge-angular2.ts)) .

I may be wrong. But give it a try and let us know if it works.

**Comment by rodneyjoyce** [comment]
Hello Ward, 

Thanks for the suggestions - FYI, I've always found your videos and posts very informative.

So I tried the top method above and I was not able to get it working.

The 2nd method looks cleaner (in terms of understanding what is happening). I'll have to wait until the export change you made is in the next NPM package (I attempted to tweak the 0.3.4 Javascript manually but was not successful).

**Comment by wardbell** [comment]
The npm package update should happen soon. I wonder why the first approach failed. Don't have time to look right now but hope to get to it.

**Comment by steveschmitt** [comment]
The [npm package](https://www.npmjs.com/package/breeze-bridge-angular2) has been updated, with AjaxAngular2Adapter now exported.  Let us know how it goes.

**Comment by rodneyjoyce** [comment]
Hi Steve, I think the package is missing some files - a new npm install only brings down 4 files (and not the changed ones) - http://screencast.com/t/yoMuNS21pzx

**Comment by steveschmitt** [comment]
Oops!  I will take a look.

Steve

**Comment by rodneyjoyce** [comment]
Thanks... ok, this is where I got to:
http://screencast.com/t/grAF6ohKT

Assuming I am using it correctly, it is complaining because authHttp does not implement 
    protected _backend: ConnectionBackend;

and therefore cannot be passed into the constructor of AjaxAngular2Adapter.

I'm going to try and tweak it a bit...

**Comment by steveschmitt** [comment]
You can cast it: `new AjaxAnuglar2Adapter(<any>authHttp)`

**Comment by rodneyjoyce** [comment]
Excellent, it works!!! Very cool, thanks a lot for all your help and quick responses...

I'll let the Auth0 guys know as well - there were a few posts on this there...

**Comment by steveschmitt** [comment]
That's great!  Can we close this now?

**Comment by rodneyjoyce** [comment]
Yes, thanks

**Comment by wardbell** [comment]
You could be more specific in casting (if you're picky like I am and want to be clear to the reader) with `new AjaxAngular2Adapter(<Http>authHttp)` or better `new AjaxAngular2Adapter(authHttp as Http)`  but it makes no practical difference. Just saying.

**Comment by rodneyjoyce** [comment]
Hmm - unfortunately I spoke a bit too soon. The Auth0 library works fine when you are already logged in and have the token however when you log out and there is no token then something is blowing up in the Auth0 library. I'm debugging it now to try and figure out the issue...  (just posting here as I mentioned this thread on some other places in case someone tries to use it)

"zone.js:388 Unhandled Promise rejection:  ; Zone: angular ; Task: Promise.then ; Value: AuthHttpError__proto__: Error undefined"

**Comment by wardbell** [comment]
Please keep us posted. Other folks are asking me about Auth0 + Breeze + Angular2

**Comment by briannoyes** [comment]
@rodneyjoyce FWIW - I also would recommend it strongly. I'm working on a Pluralsight course on combining the two right now because I have that conviction. Breeze hasn't changed much since my first Breeze course (https://app.pluralsight.com/library/courses/building-single-page-applications-breeze/table-of-contents), but that is because the IdeaBlade team did such a great job on the early versions. It is still 100% relevant for offloading the data management aspects of your SPA to a library that is great at handling all that stuff for you.

**Comment by rodneyjoyce** [comment]
Thanks for confirming Brian, and looking forward to the Pluralsight course (I've watched most of yours too ;)

**Comment by rodneyjoyce** [comment]
Ok, I have found a solution to the problem and there are no more issues as far as I can see:

Auth0 AuthHttp has a setting to continue or not (default) if there is no JWT token present (ie. unauthenticated). Normally you would use the core Http for the calls that do not require authentication and AuthHttp for the rest.

However,because it is being wrapped with Breeze you cannot make the decison on front which calls will be unauthenticated and which ones will be authententicated, therefore by default **when you are logged out** and try to use Breeze and Auth0 it will throw the "No JWT present or has expired" exception. (it will work fine when you are logged in).

To get it working you have to set the **noJwtError**  boolean in the provider so that it will ignore this (it still checks expired tokens correctly and as far as I can see has no negative effects)

```
       providers: [
            AUTH_PROVIDERS,
            provideAuth({
                noJwtError: true,
            })]
```


[https://github.com/auth0/angular2-jwt](https://github.com/auth0/angular2-jwt](https://github.com/auth0/angular2-jwt](https://github.com/auth0/angular2-jwt)
[](https://auth0.com/forum/t/fyi-using-angular2-breeze-and-auth0/4445/3)

**Comment by roydec** [comment]
Hi All,

I've used breeze before in many of my projects (even ionic). Up until now everything was fine.

For a new project I'm getting into angular-cli to setup the project.
I've installed the latest breeze-client and breeze-angular-bridge.
Everything seems to go alright until I try to fetch metadata from my Api (.net web api, breeze controller)
`this.metaDataStore.fetchMetadata(this.dataService)`
In the chrome console I get errors about Q not being defined.

> EXCEPTION: Uncaught (in promise): Error: Q is undefined. Are you missing Q.js? See https://github.com/kriskowal/q
Error: Q is undefined. Are you missing Q.js? See https://github.com/kriskowal/q
    at Function.Q (http://localhost:4200/vendor.bundle.js:21050:11) [angular]
    at MetadataStore.proto.fetchMetadata (http://localhost:4200/vendor.bundle.js:21472:16) [angular]
    at http://localhost:4200/main.bundle.js:1194:41 [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:65986:37) [angular]
    at Zone.webpackJsonp.1603.Zone.run (http://localhost:4200/polyfills.bundle.js:1408:43) [angular => angular]
    at http://localhost:4200/polyfills.bundle.js:1961:57 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:65977:37) [angular]
    at ZoneDelegate.webpackJsonp.1603.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:1644:36) [angular]
    at Zone.webpackJsonp.1603.Zone.runTask (http://localhost:4200/polyfills.bundle.js:1448:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:1811:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/polyfills.bundle.js:1702:25) [<root>]

I've in installed Q via 
`npm install --save q`
Did not resolve the issue.

Can anybody help me on this?

**Comment by briannoyes** [comment]
Sounds like you haven't setup the breeze-bridge-angular plugged in correctly. It is what does the substitution under the covers so that the Q lib should not be needed and will not be used in favor of ES2015/TypeScript promises. And also sets things up so that HTTP calls go through the Angular Http service instead of using JQuery AJAX.

All that should be required to fix that is:
1. npm install breeze-bridge-angular --save
2. import {BreezeBridgeAngularModule} from 'breeze-bridge-angular' in your app module
3. Add BreezeBridgeAngularModule to your app module imports in the NgModule directive

I'm just finishing up my Pluralsight course on Building Data Centric Apps with Angular and Breeze, and its been working fine for me since getting started late last year.

**Comment by rodneyjoyce** [comment]
Yes, Brian is correct - I have just ported it all over to Ionic2 and had the same error - once I added BreezeBridgeAngularModule to the Module it was fine.

**Comment by marcelgood** [comment]
Also wanted to mention that we just released Breeze 1.6.3 with updated type definitions. The main change is getting rid of `promises.IPromise<T>` and replace it with the ES6/TypeScript promise interface `Promise<T>` for better type compatibility. The old interface was causing assignment issues due to the additional `finally` method. For those using `Q` in non-Angular apps there's an augmentation d.ts to add the `finally` method to `Promise<T>`.

https://github.com/Breeze/breeze.js/blob/master/typescript/promise.q.shim.d.ts

**Comment by roydec** [comment]
Thank you all, I'll try it asap. I've have to setup the project again.
I've tried the instructions in the below post 
[](http://stackoverflow.com/questions/38861776/breeze-js-and-webpack)
But since angular-cli has no webpack.config I've used `ng eject` to create one.

npm start gave errors, but I guess this issue is out of this scope.

**Comment by rodneyjoyce** [comment]
@roydec  Why do you need a webpack.config? (I am also using ng CLI)

**Comment by roydec** [comment]
Hi,
I don't, but since Q was undefined, I was searching for a workaround.
By the way it is working is excpected no.

Many thanks.

**Comment by nigel-dewar** [comment]
I know this issue is closed but just had to say thank you to all the people who worked so hard on the new breeze for angular2. Looking forward to the new pluralsight course from Brian as well. Should be good as always.

**Comment by nigel-dewar** [comment]
And.. i did find setting up breeze in angular-cli worked well, and setup the sample from marcelgood 'temphire.angular' and it worked sweet. Im doing my auth using identityserver4, referencing work from damienbod. If anyones interested in seeing the identityserver4 setup just ping me.

**Comment by rastographics** [comment]
@nigel-dewar very interested in seeing as much of the identityserver4 setup as you are able to share. thank you

**Comment by nigel-dewar** [comment]
No worries will do. Just ironing out the kinks and will post a github link

**Comment by nigel-dewar** [comment]
In the meantime, if you wish to check out identityserver4 with angular2 setup, check out this guys work https://github.com/damienbod

Damien Bod. This guy is really good and has done a really great implementation of idsvr4 with angular 2 and .net core. He also posts on his blog and explains things well.

**Comment by rajsanil** [comment]
pls provide the Sample code to use token base auth with breeze  (asp.net web api) .

**Comment by nigel-dewar** [comment]
@rajsanil Hey mate, if your looking for token auth example with NG2 and .NET core, then have a look at this https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow  . uses IdentityServer4 which is good way to get token auth working for ya.

**Comment by rajsanil** [comment]
@nigel-dewar I'm looking for ng2 asp.net 4 and breeze sample code . Basically I want know how to pass header along with breeze request to server

**Comment by nigel-dewar** [comment]
@rajsanil Ok I See. I cannot help you with this sorry as I only have the experience using .net core.

**Comment by mikethibault** [comment]
Hey @rodneyjoyce , I recall visiting your post on the Auth0 forum on how to get it working with Breeze & Angular, but I think it's been lost in a forum replacement.  Could you repost it here or back on their new forum?

**Comment by briannoyes** [comment]
@mikethibault The "best" way has recently changed with the introduction of the HttpClient service (vs just Http) in 4.3. HttpClient allows you to easily hook up an HttpInterceptor that makes it much easier to add the token to the Authentication headers.

Here's an example:
```
import { AuthTokenService } from './auth-token.service';
import { AuthService } from './auth.service';
import { Injectable } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { Observable } from 'rxjs/observable';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {
  constructor(private _tokenService: AuthTokenService) {  }

  intercept (req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const token = this._tokenService.getToken();
    if (token) {
      const authReq = req.clone({
        headers: req.headers.set('Authorization', 'Bearer ' + token.access_token)
      });
      return next.handle(authReq);
    } else {
      return next.handle(req);
    }
  }
}
```
In this case the AuthTokenService is my own service component that wraps how I am getting and managing the token. In my case I'm using IdentityServer and the oidc-client library to do OpenID Connect and OAuth2. But Auth0's angular-jwt library works much the same and is probably not a bad way to go if you are just trying to work with Auth0. Same principal would apply - abstract the specifics of the token management behind a service and let the interceptor attach the token to the outbound API calls.

**Comment by briannoyes** [comment]
@mikethibault I should have also mentioned - you should switch from breeze-bridge-angular to breeze-bridge2-angular, which uses the HttpClient under the covers. So that changes the app.module import from BreezeBridgeAngularModule to BreezeBridgeHttpClientModule.

And then you add both HTTP_INTERCEPTORS and your AuthInterceptor into your module providers where the AuthInterceptor lives:
```
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AuthInterceptor } from './auth-interceptor';

@NgModule({
  imports: [... ],
  providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true},
...
```

I've been meaning to do a blog post about this. Will try to get that out in the next few days and post here when I do.

**Comment by mikethibault** [comment]
@briannoyes thanks so much!  Got Angular + Breeze + Auth0 + Web API all working together nicely now.  BTW, I'm currently most of the way through your Angular & BreezeJS course on Pluralsight.  It's great!

**Comment by TylerOrtiz** [comment]
Is there an example of getting the Breeze lab (breeze.ajaxpost) working with Angular 2+ ? Trying to import it but it's not working right.
