### ISSUE TITLE
Breeze 1.6.0 not working with Angular 1.6.0 (custom callback methods - success() and error() have been removed)

### ISSUE THREAD

**Issue by Blarm1959** [Breeze/breeze.js#177]
In Angular 1.6.0 $http's deprecated custom callback methods - success() and error() - have been removed.

Lines 16401 - 16406 in breeze.debug.js are still using success and error:

if (requestInfo.config) { // exists unless requestInterceptor killed it.
  this.$http(requestInfo.config)
      .then(requestInfo.success)
      .catch(requestInfo.error);
  this.$rootScope && this.$rootScope.$digest();
}
In the b00_breeze.ajax.angular.js files these are lines 98 - 103.

For info see: https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http

Is there a fix for this?

**Comment by Blarm1959** [comment]
Got this to work:


    if (requestInfo.config) { // exists unless requestInterceptor killed it.
      this.$http(requestInfo.config)
          .then(requestInfo.success)
          .catch(requestInfo.error);
      this.$rootScope && this.$rootScope.$digest();
    }

    function successFn(response, data, status, headers, xconfig, statusText) {
      // HACK: because $http returns a server side null as a string containing "null" - this is WRONG.
        if (response.data === "null") response.data = null;
      var httpResponse = {
        config: config,
        data: response.data,
        getHeaders: response.headers,
        ngConfig: response.config,
        status: response.status,
        statusText: response.statusText
      };
      config.success(httpResponse);
    }

    function errorFn(response, data, status, headers, xconfig, statusText) {
      // Timeout appears as an error with status===0 and no data.
      // Make it better
      if (response.status === 0 && response.data == null) {
        response.data = 'timeout';
      }
      var httpResponse = {
        config: config,
        data: response.data,
        getHeaders: response.headers,
        ngConfig: response.config,
        status: response.status,
        statusText: response.statusText
      };
      config.error(httpResponse);
    }

**Comment by mcshaz** [comment]
+1  - set up a uservoice feature request
https://breezejs.uservoice.com/forums/173093-1-breezejs-feature-suggestions/suggestions/17400706-make-breezejs-compatible-with-angular-1-6-succ

**Comment by steveschmitt** [comment]
Fixed in Breeze 1.6.1.  Thanks for suggesting the fix.
