### ISSUE TITLE
angular 2 validationErrors throws exception in IE11

### ISSUE THREAD

**Issue by djleonskennedy** [Breeze/breeze.js#188]
Hello

Have issue with validationError in **IE11**, in other browsers all goes fine, no breeze validation is used

![image](https://cloud.githubusercontent.com/assets/8366455/23592077/236af308-0204-11e7-8a28-9db0636461cb.png)

loading entity its renders fine but error occurs

Please advice. after error app cannot do any CRUD operation

Thank you

**Comment by marcelgood** [comment]
Need more information. Check the `entityErrors` collection as mentioned in the error to see what the validation errors are. That should lead you to what's wrong with the entities.

**Comment by djleonskennedy** [comment]
Found in validation array that `edited` cannot be null, however in other browsers all goes fine, why IE11 produces an error?

**Comment by marcelgood** [comment]
You would have to post a small example that demonstrates what you are seeing. There are always differences between browsers. I'm not aware of any issues regarding validation between browsers, so I suspect there's something else in your code that behaves differently on IE11 vs other browsers. So far you haven't provided enough information to help you.

**Comment by djleonskennedy** [comment]
i'll try to investigate it more detail, thank you

**Comment by djleonskennedy** [comment]
@marcelgood Problem was about `toLocalString()` on Date instance, string as output, however you can check this issue cause it's different behavior in different browsers

**Comment by steveschmitt** [comment]
Thanks for looking into it.  Is the `toLocalString()` call something in Breeze, or in your own custom validator?

**Comment by marcelgood** [comment]
This must be something in your code. I just scanned the Breeze code base and we are not using `toLocalString`. `toLocalString` is not supported in IE as far as I can see. It depends on the international API, which has limited or no support in certain browsers. There's a polyfill to add this functionality to browsers that don't support it.

https://www.npmjs.com/package/intl

**Comment by djleonskennedy** [comment]
@marcelgood copy that, thank you
