### ISSUE TITLE
Error when using with Angular4

### ISSUE THREAD

**Issue by rodneyjoyce** [Breeze/breeze.js#192]
Anyone using Breeze with ng4 yet? 

I have upgraded to Angular4 and am getting an error when using Angular CLI 1.0 'ng serve':

Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported:

https://www.screencast.com/t/E0VZQX7R2

**Comment by marcelgood** [comment]
I have to look into what's it gonna take to make the `breeze-bridge-angular` module work with Angular v4. Looks like it's not AOT compatible in its current form. BTW, you are using an old package. `breeze-bridge-angular2` is deprecated. The new package is `breeze-bridge-angular`.

**Comment by marcelgood** [comment]
I just published `breeze-bridge-angular@4.0.0-alpha1`. This should fix the error. Go ahead on `npm uninstall breeze-bridge-angular2 -S`, followed by `npm install breeze-bridge-angular@4.0.0-alpha1 -S` and let me know if it works.

**Comment by rodneyjoyce** [comment]
Thanks for the quick response - I had to roll everything back to ng2, but I will try again later today and post back here

**Comment by rodneyjoyce** [comment]
Ok, I have successfully upgraded to ng4 using breeze-bridge-angular@4.0.0-alpha1 - everything works great, thanks.
