### ISSUE TITLE
Not easy to export to IndexedDB

### ISSUE THREAD

**Issue by bramski** [Breeze/breeze.js#20]
![screen shot 2014-06-19 at 6 34 14 pm](https://cloud.githubusercontent.com/assets/421781/3335727/0a3318ca-f81b-11e3-87df-045ea2cd665a.png)

The export/import page linked to from there has no mention about 'how' you should export & import from indexedDB.  export/import just gives you a GIANT STRING.  That doesn't really make any sense to export to an indexedDB database where you really want to take all your entities and put them into the objectStore keyed properly.

**Comment by wardbell** [comment]
Hi Bram. 

Jay was adamant that we NOT add a new method to `EntityManager`. He did approve extending `EntityManager.exportEntities` to support the JSON output and the EntityType selection.

The extension involves replacing the 2nd parameter with a configuration object, defined as follows with default values

    {
        asString: true
        includeMetadata: true
    }

Accordingly, the example above should be updated:

   var exp = em1.exportEntities(typeNames, {asString: false, includeMetadata: false});

The former boolean parameter is still supported but deprecated:

    // export the entities of those types as a STRING (default) and without metadata
   var exp = em1.exportEntities(typeNames, false);  // deprecated

The now proper way to have expressed this would be:

    // export the entities of those types as a STRING (default) and without metadata
   var exp = em1.exportEntities(typeNames, { includeMetadata: false});

It's in github now. We expect to release this in v.1.5.3.

I look forward to working with you on the wrapper methods for the indexDb solution (as we discussed) when you're ready to pursue that.

**Comment by wardbell** [comment]
Haven't heard from you since we updated export/import. Closing until you come back with something to the contrary.

**Comment by bramski** [comment]
Thanks for your work on this @wardbell.  Not sure when I will get some running room to look into this.  I am onto some new projects for a bit and this has been tabled for the time being.  Cheers.
