### ISSUE TITLE
Trailing zero's is being removed for decimal values

### ISSUE THREAD

**Issue by mkhan2016** [Breeze/breeze.js#205]
We would like to preserve the user input decimal value and save it to the database. This works fine for the cases like,

1.001, 1.0001, 1.100001

But don't work for below

1.000, 1.0, 1.0000000 

Above values becomes **1** and here we lose the original entered value from the user.

We are using AngularJS + BreezeJS on front end which is talking to EntityFramework API.

**Current Investigation**

When we set the value from frontend to Breeze entity. It goes into a function 'coerceToFloat' which trim trailing zeros from decimal.

_Breeze.debug.js _

var coerceToFloat = function (source, sourceTypeName) {
  if (sourceTypeName === "string") {
    var src = source.trim();
    if (src === "") return null;
    var val = parseFloat(src);
    return isNaN(val) ? source : val;
  }
  return source;
};

It's pretty hard to handcraft something into the BreezeJS library for this case, surely it will be much easier if BreezeJS can handle this use case.

_Is there any recommendation how can we proceed with out modifying original BreezeJS functions?_

**Comment by marcelgood** [comment]
You will have to change the data type of your property and database column to string and save the value as a string. Breeze has to coerce it to match the data type of the property and most languages JS, C# etc. will trim trailing zeros. Ultimately, your DB will trim the trailing zero as well when storing the float.
