### ISSUE TITLE
ComplexType TypeScript constructor definition is missing config parameter

### ISSUE THREAD

**Issue by ravalum** [Breeze/breeze.js#209]
I'm writing Metatdata by hand for a project that need it, I'm facing an issue to declare ComplexType.

In JS the ComplexType constructor need a config object : 
`var ctor = function ComplexType(config)`

In the TypeScript definition the ComplexType have no constructor define with a config object : 
```
    export class ComplexType implements IStructuralType {
        complexProperties: DataProperty[];
        dataProperties: DataProperty[];
        name: string;
        namespace: string;
        shortName: string;
        unmappedProperties: DataProperty[];
        validators: Validator[];
        addProperty(dataProperty: DataProperty): ComplexType;
        getProperties(): DataProperty[];
    }
```

This can be fix by adding a ComplexTypeOptions interface and add a constructor to the ComplexType definition.
```
    export interface ComplexTypeOptions {
        shortName?: string;
    }
    export class ComplexType implements IStructuralType {
        complexProperties: DataProperty[];
        dataProperties: DataProperty[];
        name: string;
        namespace: string;
        shortName: string;
        unmappedProperties: DataProperty[];
        validators: Validator[];
        addProperty(dataProperty: DataProperty): ComplexType;
        getProperties(): DataProperty[];

        constructor(config: ComplexTypeOptions);
    }
```

Does someone already in the project can check if I'm right and make the changes ?
I don't want to make a pull request for so small changes.

Thanks.

**Comment by marcelgood** [comment]
Thanks for letting us know. I've fixed the type definition.
