### ISSUE TITLE
Call Breeze Controller with Windows authentication

### ISSUE THREAD

**Issue by janminarik** [Breeze/breeze.js#212]
I need call ASP.NET Web API Breeze controller which use Windows authentication from Angular 5 / Breeze app.

I tried some modification for ajaxAdapter

1. Option

```
	import { config } from 'breeze-client';

        let ajaxAdapter = <any>config.getAdapterInstance('ajax');
        
        ajaxAdapter.defaultSettings = {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            withCredentials: true
        };
```

2. Option

```
	import { config } from 'breeze-client';

        let ajaxAdapter = <any>config.getAdapterInstance('ajax');

        ajaxAdapter.defaultSettings = {
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            },
            xhrFields: {
                withCredentials: true
            }
        };
```
		

Not work.

Request header doesn’t contains Authorization: NTLM ...

When I call Web API controller (no Breeze) which also require Windows authentication with Angular HttpClient it works.

        const headers = new HttpHeaders({
            'Content-Type': 'application/x-www-form-urlencoded'
        });

        this._httpClient.get(url, { headers, withCredentials: true }));
		

Request header contains Authorization: NTLM ...

Web Client:

    "@angular/core": "^5.0.0",
	"typescript": "~2.4.2"
    "breeze-bridge-angular": "^4.0.2",
    "breeze-client": "^1.6.3",

Any Idea?

**Solution:**

Use https://github.com/Breeze/breeze.bridge2.angular + angular HttpInterceptor

**Comment by marcelgood** [comment]
Duplicate. https://github.com/Breeze/breeze.bridge.angular/issues/18
