### ISSUE TITLE
Alternate foreign keys incorrectly updated on navigation property entities

### ISSUE THREAD

**Issue by fulte004** [Breeze/breeze.js#214]
In breeze.debug.js, on line 5405 in setNpValue, the statement:
`var inverseKeyProps = property.entityType.keyProperties;`
incorrectly assigns the inverse property's key properties and the result is that the primary key values of the inverse navigation property are assigned to the foreign key properties instead of their original values and data is corrupted.
Consider the following scenario:
A Department object has an Id primary key, a DeptId alternate foreign key that is unique, and a navigation property of DepartmentMembers, an array of class DepartmentMember that has an Id (primary key), DeptId related to Department.DeptId, and a MemberId.
In this scenario instead of the original value of DeptId being used upon loading into the navigation property, setNpValue will assign the Department.Id value to DepartmentMember.DeptId instead of  correctly maintaining the inverse foreign key mapping of Department.DeptId to DeparmentMember.DeptId, resulting in corrupted data.
updating the statement on line 5405 as follows fixes this issue:
` var inverseKeyProps = property.entityType.inverseForeignKeyProperties;`

**Comment by mroeling** [comment]
Can you confirm that the navigation property is of the non-scalar type? I experience a similar problem, but only when the property is a collection.

**Comment by fulte004** [comment]
Correct. the isScalar property is false because it is a list/array for a one-to-many relationship.  I did get everything working for navigation properties both one-to-many and one-to-one, but I did have to modify Breeze to do it. I'm pressed for time on a project, but once I have it completed, I will be making a pull request with the modifications.

**Comment by mroeling** [comment]
Was this your only change?

**Comment by fulte004** [comment]
In Breeze Client, the function resolveRelated was also a problem. It was not really necessary for my entities to get their navigation properties properly assigned and it was actually causing things that were otherwise correctly configured to fail. I modified it to fix that, but I'm not satisfied that I'm done with it yet. I moved on because I got everything working, but there was a reason it was placed in the code and I need to make sure that I'm not breaking another functionality used by a different case, whatever that may be. 

The other part of the issue had to do with the ASP.NET Core Metadata builder code. It was not sending the correct foreign keys, which was another big part of the issue.  Once I corrected that, and the client code, everything works perfectly for one-to-one and one-to-many relationships.  I'm almost wondering if the resolveRelated wasn't intended for many-to-many relationships, which their documentation says they currently don't support. This could be why.  I need to communicate with the IdeaBlade team and learn more.

**Comment by steveschmitt** [comment]
@fulte004 I'm finally looking into this!  Can you tell me what changes you made to the ASP.NET Core MetadataBuilder code?

**Comment by fulte004** [comment]
@steveschmitt Wow! I had forgotten about this.  My issues were resolved using the latest versions of breeze-client.js and Breeze Server 3.x.  I'm now on breeze-client 2.0.9 and Breeze Server 5.0.4 and everything works for me without modifications of the current NPM and NuGet packages.  I think you can stick a fork in this one.

**Comment by steveschmitt** [comment]
I was able to reproduce the problem in tests, and have fixed in breeze-client 2.1.1.
Now Breeze supports relationships to foreign keys that are not the PK.
