### ISSUE TITLE
index.d.ts custom metadata properties missing

### ISSUE THREAD

**Issue by Dan-Goodwin** [Breeze/breeze.js#216]
The custom?:{} property is missing from the IStructuralType & IProperty interfaces and their NavigationProperty, DataProperty, ComplexType & DataProperty class implementations.

Additionally, the MetadataStore class getEntityType() and getEntityTypes() specify a return type of the partial IStructuralType implementation instead of the full EntityType class.

**Comment by marcelgood** [comment]
I've added the custom property.

`getEntityType()` and `getEntityTypes()` however don't just return `EntityType`. They also return `ComplexType`. The initial d.ts was authored before TypeScript supported union types. I've updated the declation to use `EntityType | ComplexType` whereever `IStructuralType` was used to make it more obvious. 

E.g.

`getEntityType(entityTypeName: string, okIfNotFound?: boolean): EntityType | ComplexType;`
