### ISSUE TITLE
Attribute DefaultValue is checked against null with == leads to exception in entity-metadata

### ISSUE THREAD

**Issue by PatrizioR** [Breeze/breeze.js#218]
See [odata ](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752535)

Says if there is no defaultValue, client should not assume one.

At entity-metadata.ts line 2055
` if (this.defaultValue == null) {
   ...
}`

checks on null with == instead of === (since it could be undefined), leads to error for metadata:
`<Property Name="validFrom" Type="Edm.Date" Nullable="false"/>`

Since it does not provide a default value and is not nullable.

Is this an issue? Changing == to === fix this issue for me.

**Comment by phunksta** [comment]
I also have this issue, in almost exactly the same circumstances.
In addition, with current odata v4 support in .NET WebApi, it doe snot seem possible to pass a 'defaultValue' attribute in the metadata so that is not a possible workaround.

**Comment by steveschmitt** [comment]
Fixed in breeze-client 2.1.0
