### ISSUE TITLE
breeze.js repo vs. breeze-client repo

### ISSUE THREAD

**Issue by flyfishMT** [Breeze/breeze.js#222]
Hi all, 
It looks like you have two repos described as "Breeze for JavaScript clients".  
What is difference?
Which one should we use?
Thanks

**Comment by flyfishMT** [comment]
Sorry, I see that breeze-client is your upcoming release.  Any ETA?  Thanks.

**Comment by steveschmitt** [comment]
Still in alpha.  Just updated to support ES6 and Angular 8.  Please `npm install breeze-client@next` and give it a try.

**Comment by steveschmitt** [comment]
Breeze client is released.  Current release is 2.1.0.
