### ISSUE TITLE
Entities not coming back as Breeze entities

### ISSUE THREAD

**Issue by FlynnMarlie** [Breeze/breeze.js#224]
Hi,

We have created a .Net Core Angular project in Visual Studio 2017 that uses Breeze to get entities from a SQL Server 2014 database. When the entities are retrieved, just the objects themselves are returned. Items such as _entityAspect_, that usually form part of Breeze entities, are missing on the entities.

This leaves us unable to use Breeze to perform operations such as modifying and then saving the entity back to the database since the _entityAspect_ object is missing (see image below). Is this a bug or are we doing something wrong?

We are using the following versions of Breeze:

- Client side: 
breeze-client: v1.7.1

- NuGet Packages:
Breeze.AspNetCore.NetCore: v1.0.3
Breeze.Persistence.EFCore: v1.0.3

![image](https://user-images.githubusercontent.com/30813912/60641837-efe81180-9e70-11e9-823c-eac1cf44cfed.png)

A sample project, replicating the issue:

[BreezeWebApplication.zip](https://github.com/Breeze/breeze.js/files/3357578/BreezeWebApplication.zip)

**Comment by Davidvlv** [comment]
It seems to be something to do with the name of the [BreezeQueryFilter] function in the DeploymentController.cs file - In the sample If the name of the Controller method is WeatherForecasts, the promise doesn't return with the breeze entities attached to the results, but if the name is Customer (Matches the database table/entity name), then it returns as expected with the entities.

This didn't use to be the case - you could have any name for controller methods, and it's a problem, as it's breaking our preexisting controller methods.

**Comment by steveschmitt** [comment]
The problem appears to be that the JSON coming back from the server does not have the `$id` and `$type` properties that Breeze expects.  So you need to change the JSON option setup in `Startup.cs` (line 39 in the sample code that @FlynnMarlie provided).

Breeze.Core has a convenience function that sets up the correct values:

    services.AddMvc().AddJsonOptions(options => {
        Breeze.Core.JsonSerializationFns.UpdateWithDefaults(options.SerializerSettings);
    });

One catch is that the default options do camelCasing of the property names by default, but if your Breeze _client_ expects to do the case conversion via its client-side naming convention, then you should turn camelCasing _off_ on the server.  So then in your Startup.cs you would have:

    services.AddMvc().AddJsonOptions(options =>
    {
        var ss = Breeze.Core.JsonSerializationFns.UpdateWithDefaults(options.SerializerSettings);
        var resolver = ss.ContractResolver as Newtonsoft.Json.Serialization.DefaultContractResolver;
        if (resolver != null)
        {
            resolver.NamingStrategy = null;  // remove json camelCasing; names are converted on the client.
        }
    });

Hope this helps.

**Comment by FlynnMarlie** [comment]
@steveschmitt, I've followed your advice and it works perfectly. Thank you so much for your help!!

**Comment by graphicsxp** [comment]
I've come across this issue.  Using the fix above is working for breeze controllers. But what about non-breeze controllers ? Now with this strategy, they are returning properties in my json objects as upper case. Is there a way to make both work with camel casing ?
