### ISSUE TITLE
Chrome 77 & fetchMetadata - Promise.prototype.then called on incompatible receiver

### ISSUE THREAD

**Issue by jasechong** [Breeze/breeze.js#227]
With the latest Chrome 77, the fetchMetadata method sends the request out and gets a response, but Chrome throws this error:

```
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver
```

Top of callstack (calls in stream-http):

```
push../node_modules/stream-http/lib/response.js.exports.IncomingMessage	@	response.js:68
ClientRequest._connect	@	request.js:251
(anonymous)	@	request.js:147

```
It works in previous version of Chrome with exactly the same code.   Anyone else seeing this problem?  

Versions:

```
    "breeze-client": "1.7.1",
    "breeze-odata4": "0.9.14",
    "stream-http": "3.0.0",
```

**Comment by marcelgood** [comment]
I just tried our reference app on Chrome 77, and I don't see this. If I had to guess, then it's probably caused by one of the other libs you are using. The breeze-odata4 lib is not ours, and since it installs a third-party uriBuilder and dataService, that would be my first place to start.

**Comment by steveschmitt** [comment]
Just from the error message, it sounds like there may be two incompatible Promise implementations.   Chrome native ES6 promises vs Q promises, for instance.

**Comment by jasechong** [comment]
Thanks for the replies and suggestions.   

FYI, tracked it down to dependency on WritableStream and ReadableStream, which has recently been refactored in Chrome as part of a StreamsNative feature (see https://bugs.chromium.org/p/chromium/issues/detail?id=902633).
