### ISSUE TITLE
Promise returned from Breeze not triggering Angular change detection in Chrome incognito

### ISSUE THREAD

**Issue by Davidvlv** [Breeze/breeze.js#229]
We are having an issue in our Angular application where change detection is not being triggered in Chrome incognito mode. Unsure if this is an issue with breeze or something else, but any help would be appreciated.

A cut down sample of our code is as follows:
```js
@Component({
    template: "<div *ngIf="loading">loading...</div>"
})
export class MyPage implements AfterViewInit {
    // this is the variable that change detection needs to detect
    loading: boolean = true;
    public manager: EntityManager;

    constructor() {
        this.manager =new EntityManager({
            dataService: new DataService({ serviceName: 'snippity/snip', uriBuilderName: 'json' })
        });
        this.manager.fetchMetadata();
    }

    ngAfterViewInit(): void {
        let sub = this.zone.onStable.subscribe(() => {
            sub.unsubscribe();
            this.load();
        });
    }

    load() {
        let promise = this.manager.executeQuery(EntityQuery.from("Snip"));

        Promise.all([promise])
            .then(allRes => {
                this.loading = false; // <-- this doesn't get detected by change detection, and the html never updates
            });
    }
```

Thanks

**Comment by marcelgood** [comment]
I'm not seeing any issues in the latest Chrome 83 Incognito mode with our reference app.

https://github.com/Breeze/temphire.angular

Can you repro the issue with TempHire or send a running example? Our TempHire example is currently on Angular 8 with Breeze 2. Not quite the latest versions, but never seen an issue in Incognito mode. Are you using the Breeze Angular bridge?

**Comment by Davidvlv** [comment]
Hi, we are using Angular 5.2.11 and breeze-client 2.0.0. We are not using breeze angular bridge.

I will try to get an example running.

**Comment by marcelgood** [comment]
Yeah, w/o the breeze angular bridge we can't guarantee that it works. The bridge makes sure Breeze is properly hooked into Angular and you are on quite an old version of Angular. Also just out of curiosity, why are you loading data in ngAfterViewInit()? The change detection cycle is done at that point. You should load data in ngOnInit().

**Comment by Davidvlv** [comment]
I'm not sure why we're using ngAfterViewInit, I will investigate further and also look into the angular bridge.

Thanks

**Comment by marcelgood** [comment]
BTW, in Breeze 2 it's no longer called the Breeze Angular bridge. You'd be using `AjaxHttpClientAdapter` instead, which ships as part of Breeze 2.

**Comment by steveschmitt** [comment]
Closing this here.  Please open an issue in the [breeze-client](https://github.com/Breeze/breeze-client) repo if there is still a problem.
