### ISSUE TITLE
MergeStrategy.PreserveChanges

### ISSUE THREAD

**Issue by vikasprogrammer** [Breeze/breeze.js#52]
I am using AngularJS + JSON datasource + metadata by hand. When I try to fetch a query, it throws me error : 

`A MergeStrategy of 'Disallowed' does not allow you to attach an entity when an entity with the same key is already attached: hosts:#-1`

This is my query

    
    query = breeze.EntityQuery.from('hosts').expand('ports'); 
    query = query.using(breeze.MergeStrategy.PreserveChanges);
    manager.executeQuery(query).then(..)
    

When I hardcode `MergeStrategy` within the breeze.debug.js file (line number 12475) and make it PreserveChanges, it works perfectly!

PS: When used without expand it works perfectly without code modification. 

Not sure why is the error.

**Comment by wardbell** [comment]
Closing because we think we have fixed it and have not heard any follow up from you. Happy to re-open if you have something for us.
