### ISSUE TITLE
manager.hasChanges with entity types not present in the manager 1.5.2

### ISSUE THREAD

**Issue by novice3030** [Breeze/breeze.js#58]
When calling manager.hasChanges(['EntityType1','EntityType2'])
and the manager doesn't contain entities of EntityType2 type an undefined exception is thrown in line 1365 a50_entityManager.js

**Comment by wardbell** [comment]
Thanks for encircling the problem. The clue was your use of the type filtering in `.hasChange('someType')`.  Once I saw that I isolated the problem easily. It is fixed in github and will appear in the next release.

Thanks.
