### ISSUE TITLE
Breezejs and Highcharts

### ISSUE THREAD

**Issue by MikaelGRA** [Breeze/breeze.js#60]
This issue is related to web applications using breezejs and Highcharts (and possibly other libraries that use the property "x" on objects. Explanation below).

Spent the last two days tracking a bug that caused the Highcharts graph library to behave strange. It would often cause the "draw" behaviour of it to behave incorrectly, not displaying for example the correct graph or tooltip.

Turns out that when I removed the breezejs library the issue would simply go away. So I debugged a bit in breezejs and it turns out the following statement (which appears two places throughout breeze):

Object.defineProperty({}, 'x', {})

Causes the issue. For me, changing 'x' to something else fixes the issue.

It is worth noting that the observed behaviour actually only occurrs in Chromium-based browsers (Chrome, Opera), which makes the issue that more strange.

If you don't want to take my word for it, I would be happy to provide a more detailed bug report with steps to reproduce, but it is a bit tricky to provide this, because the bug occurrs "inconsistently".

**Comment by wardbell** [comment]
Weird indeed! I don't want to spend too much time on this. I have a feeling it's just a test to see if the browser supports defineProperty in which case any name would do. I'll peek at it later today.

But it is so bizarre as that property should never have leaked out. Do you think its worth discovering why Hightower is vulnerable to something so obscure? Sounds like their bug to me.

**Comment by steveschmitt** [comment]
I don't know why this is affecting Highcharts, but it looks like breeze is missing a set of parentheses.  Try changing line 37 of your breeze.debug.js to include the outer parens, like this:

	var __isES5Supported = function () {
	  try {
	    return !!(Object.getPrototypeOf && Object.defineProperty({}, 'x', {})); // outer parens added
	  } catch (e) {
	    return false;
	  }
	}();

Without the outer parens, `__isES5Supported` was an object with property 'x'.  With the parens, it's a boolean.

If you can, please try that change and see if it fixes your Highcharts problem.  Thanks!

**Comment by wardbell** [comment]
Thanks, Steve. Clearly a bug regardless. I'm fixing it in both places and checking it in now.

**Comment by MikaelGRA** [comment]
I can confirm the additional paranthesis suggested by @steveschmitt fixes my issue with Highcharts. So @wardbell can consider this fixed.

Thank you.
