### ISSUE TITLE
Breeze typescript definitions for angular using ng.IPromise

### ISSUE THREAD

**Issue by nelsonmorais** [Breeze/breeze.js#62]
Hi,

I'm looking for the right place to get the typescript definitions for breeze that are compatible with angular ng.IPromise.

In the https://github.com/borisyankov/DefinitelyTyped we can find only one typescript definition, the one that uses Q. I don't want to use this one, but is the only one that can be installd via TSD (npm package), and TSD seems to be the right tool for this these days.

In the https://github.com/eggers/dt-breeze-angular I can find one that was updated to use the ng.IPromise but as it is not in the https://github.com/borisyankov/DefinitelyTyped so I can't use TSD to install it. It also seems to be outdated when compared to next one (following paragraph).

I've found another d.ts at https://github.com/Breeze/breeze.js/tree/master/typescript/typescript wich seems to be the most up to date version as it doesn't use Q.d.ts anymore and uses breeze.Promises.IPromise.

I guess the last one should be the right one, but I still need to know if this one is compatible with the angular promises. If this is the right one, shouldn't it be at the https://github.com/borisyankov/DefinitelyTyped repository wich is where most of the d.ts are and is where the TSD is looking for them?

Thanks,
Nelson Morais

**Comment by steveschmitt** [comment]
The last one you mentioned, https://github.com/Breeze/breeze.js/tree/master/typescript/typescript , is the most up-to-date version.  It is compatible with Angular promises.

You are right, we will make sure that DefinitelyTyped gets the up-to-date version.

**Comment by nelsonmorais** [comment]
Thanks! Can you post a message here when done?

**Comment by nelsonmorais** [comment]
Hi Steve,

Can you tell when do you expect to have the correct .d.ts in the https://github.com/borisyankov/DefinitelyTyped repository?

Thanks!

**Comment by steveschmitt** [comment]
The pull request has been submitted to DefinitelyTyped.  I will let you know when it is complete.

**Comment by nelsonmorais** [comment]
Thanks!

**Comment by steveschmitt** [comment]
The commit has been merged on DefinitelyTyped, so it is now in sync with the one in breeze.js
