### ISSUE TITLE
isNavigationPropertyLoaded returns undefined on imported entites

### ISSUE THREAD

**Issue by bbobrian** [Breeze/breeze.js#67]
breeze.js 1.5.2

Title pretty much says it all, but here is the scenario:

1) Have an existing EntityManager with an entity that needs to be edited.
2) Create a second EntityManager to act as an editing/undo context.
3) Export/import entity (and it's related entities) from first to second EntityManager
4) The same editor code is used in multiple places, and sometimes certain navigation properties may not have been loaded depending on the path taken to get to the editor.
5) Upon trying to check entity.entityAspect.isNavigationPropertyLoaded('property') the result is undefined. This will be the case whether the related entities have been loaded or not.

Everything works correctly in the initial EntityManager that loaded the entity.

**Comment by wardbell** [comment]
Looking into it ... finally

**Comment by wardbell** [comment]
Confirmed with[ the API Docs](http://www.breezejs.com/sites/all/apidocs/classes/EntityAspect.html#method_isNavigationPropertyLoaded) that `entity.entityAspect.isNavigationPropertyLoaded` should not be set `true` for a **collection** navigation property after `importEntities` *even if it returned values*.

Confirmed in reality with two [new DocCode tests](https://github.com/Breeze/breeze.js.samples/blob/master/net/DocCode/DocCode/tests/exportImportTests.js#L165) "Import of entity graph does NOT set `entity.entityAspect.isNavigationPropertyLoaded`" and "Local creation of entity graph does NOT set `entity.entityAspect.isNavigationPropertyLoaded`"

The point of `isNavigationPropertyLoaded`is that "loaded" means "came from server".

You can force the `isNavigationPropertyLoaded` to be `true` by calling [`markAsLoaded`](http://www.breezejs.com/sites/all/apidocs/classes/EntityAspect.html#method_markAsLoaded)  if you have reason to override Breeze's determination.

There is a different rule for **scalar** navigation properties (nav props that return at most a single value). For **scalar** navigations, `entity.entityAspect.isNavigationPropertyLoaded` returns whether or not there is a value.

>I'm pretty sure we should NOT have made this exception. The value could have been set locally when in fact there is no corresponding server value.
>
>Perhaps worse, the value could still be null **after** loading ... because the server has no such value for this property ... and yet `isNavigationPropertyLoaded` would report that you had not loaded the property.
>
>I will take this issue up with my colleagues.
