### ISSUE TITLE
Bower package for version 1.5.3 has the contents of version 1.5.2

### ISSUE THREAD

**Issue by nelsonmorais** [Breeze/breeze.js#69]
Hi,

I've just installed the breezejs bower package for version 1.5.3 but the contents are the same as the 1.5.2 version.

I've looked at the bower cache contents and the file breeze.debug.js still has this code:

    var breeze = {
        version: "1.5.2",
        metadataVersion: "1.0.5"
    };

The code on github for version 1.5.3 has:

    var breeze = {
        version: "1.5.3",
        metadataVersion: "1.0.5"
    };

Can you please check if the package was built correctly?

Thanks,
Nelson Morais

**Comment by wardbell** [comment]
The problem most likely is that you have a cached copy of "breeze-client" v.1.5.3.

It is most likely my fault. A while back I pushed a prelim of 1.5.3 with the "1.5.3" tag; that version had a 1.5.2 breeze.debug.js in it. Anyone who happened to install that version would have the "old" code.  When we did the real 1.5.3 release, I just moved the "1.5.3" tag forward a few commits. I know you're not supposed to do this but ... well what can I say. I decided better to have "1.5.3" tag aligned with our official release number and risk the problem you're having.

The resolution is simple: clear your bower cache and re-install:

    bower cache clean
    bower install breeze-client

**Comment by nelsonmorais** [comment]
Thanks Ward,

In fact the problem was mine, because I didn't read the docs as I should have :(. I was still using the "breezejs" bower package instead of the new one "breeze-client".

Nevertheless, the deprecated "breezejs" 1.5.3 package has the version 1.5.2, but as it is mentioned in the documentation (http://www.getbreezenow.com/documentation/release-notes#breeze-client-news) this package is now deprecated and it stopped at version 1.5.2.

Thanks!
