### ISSUE TITLE
Question on intergration with AngularJS and RequireJS

### ISSUE THREAD

**Issue by theocoria** [Breeze/breeze.js#78]
Hi,

I've only recently started looking at Breeze and I love the idea, so awesome work....

I am looking at integrating Breeze into our Angular App, but I'm struggling to get it working. We use RequireJS. The articles I've been able to find only focus on a very simple Angular app or it uses Knockout....

Can you please steer me in some sort of direction so that I can start injecting breeze into my application?

Thanx in advance.

**Comment by wardbell** [comment]
Making *any* Angular app work with require.js has its challenges, especially if you're hoping to use require for dynamic module loading.

In my limited experience, all of those challenges are Angular related. Breeze is just another module to be loaded, presumably at the start.

The web has many discussions of Angular + Require. I think my friend Dan Wahlin has written about it. 

Most Breeze apps these days are Angular apps. There are many resources available that cover that relationship including on the Breeze documentation. A little web searching should get you going.

Let us know if there are specific issues we can address.

**Comment by theocoria** [comment]
I have had my fair share of looking at the articles and help out there. The thing is, I have a enterprise level product well on its way using requirejs and angular, and I am able to load everything else fine, just really struggling doing the same with Breeze. Thanks for the reply, I will soldier on and see if I can manage to get it right. Please let me know if you know what the injection with requirejs looks like.

**Comment by wardbell** [comment]
Can you describe what is going on? You should be able to require breeze and breeze.bridge.angular (which depends on breeze) in the usual manner.

**Comment by Phoscur** [comment]
I can confirm that Breeze+Angular+RequireJS works together. I'm keeping breeze out of my mangled production file but everything else works fine.
Sadly RequireJS is ofthen complicated to configure with all the might it comes.
