### ISSUE TITLE
Replace some-function with for-loop for better performance

### ISSUE THREAD

**Issue by Skielex** [Breeze/breeze.js#82]
When getting sets of entities from the data manger (eg. `getChanges`) the `getFilter` function from [entityGroup.js](https://github.com/Breeze/breeze.js/blob/a23d257535618d558910724107fb31c73af41057/src/a50_entityGroup.js) is used to filter the entities. The following piece of code is called for every entity:

``` javascript
        return entityStates.some(function (es) {
          return e.entityAspect.entityState === es;
        });
```

While doing some testing I found that this piece of code performed quite poorly, particularly in IE11. Since it may be called a lot, I found the performance could be much improved by changing the code to a simple for-loop:

``` javascript
        for (var i = 0; i < entityStates.length; i++) {
          if (entityStates[i] === e.entityAspect.entityState) {
            return true;
          }
        }
        return false;
```

In the particular case of `getChanges` another way to improve performance a fair bit (~x3) would be to reverse the filter test. Right now it tests for every entity if it's `Added`, `Deleted` or `Modified`. In reality all it needs to test is if the entity state is NOT `Unchanged`.

**Comment by wardbell** [comment]
I have submitted changes that optimize for the "has changes" case and the switch to the for-loop that you suggested. I expect these changes to be accepted and published in our next release.

Thanks for highlighting this issue.  I'll close it once the improvements are released.

**Comment by Skielex** [comment]
Sounds great. Thanks for your quick response :)

**Comment by Skielex** [comment]
I assume this was updated long ago :)
