### ISSUE TITLE
Pass multiple predicates as array doesn't work

### ISSUE THREAD

**Issue by rapmue** [Breeze/breeze.js#86]
As stated in the official [documentation](http://www.breezejs.com/sites/all/apidocs/classes/Predicate.html), I tried to use something like this:

```javascript
var counter = 2; //variable count
var firstPredicate = new Predicate(...);
var preds = [];
for(var i = 0; i < counter; i++) {
     preds.push(Predicate.create(...));
}
var newPred = firstPredicate.and(preds);
```

analoge to the example with

```javascript
var preds = [p1, p2, p3];
var newPred = Predicate.and(preds);
```

The problem is, that as soon as `counter` is bigger than 1 there is an exception. (breeze version 1.5.3)

```
TypeError: Cannot read property 'operator' of undefined
    at createPredicateFromArray (breeze.debug.js:9991)
    at createPredicateFromArray (breeze.debug.js:9995)
    at ctor (breeze.debug.js:9712)
    at ctor (breeze.debug.js:9710)
    at proto.or (breeze.debug.js:9879)
```

As I digged into the methods, i noticed, that at line 9981 is a TODO comment which could eventually solve this issue.
But in my opinion it should be somewhere near 9710 where an instance of a predicate is returned.

I tried to solve this issue, but i didn't exactly understand how the nesting works. (how does someone know if the predicates are linked with or/and etc. at this level?)

**Comment by wardbell** [comment]
Definitely a disconnect between what the API document says you can do and what is actually allowed. Looking into it.

**Comment by wardbell** [comment]
I believe we are on our way to a fix which (if I am correct) should arrive in the next release (v.1.5.4?)

**Comment by rapmue** [comment]
Thanks, I tested both cases in my app and it seems like everything is working as expected now.
