### ISSUE TITLE
Angular Breeze date dirty checking mismatch

### ISSUE THREAD

**Issue by brunoAltinet** [Breeze/breeze.js#9]
the root of the problem is presented in this post on stackoverflow:

http://stackoverflow.com/questions/21762686/uibootstrap-and-angularjs-datepicker-tabbing-and-direct-entry/23792768#23792768

And i also propose a solution.
Thank you!

**Comment by wardbell** [comment]
Closing for lack of follow up from you. Happy to re-open if you have something to talk about.
