### ISSUE TITLE
Use breeze.js inside node.js

### ISSUE THREAD

**Issue by eXon** [Breeze/breeze.js#95]
I am building an isomorphic application and I want to be able to use Breeze.js as my data manager. My problem is if I want to be able to pre-render my ReactJS application server-side, I need to be able to fetch the data using BreezeJS (the client) and it is running inside node.js instead of the browser.

Is it possible to remove all the dependencies from `window`? (or at least not crash if their is none) It seems like their is very few and if you think it is a good idea I would be very happy to create a PR.

**Comment by wardbell** [comment]
We are using Breeze.Client on Node ourselves. Look at this ["breeze-client" npm package](https://www.npmjs.com/package/breeze-client). I didn't think we depended on `window` but you're welcome to point out where we do.

>I did a quick search in *breeze.debug.js* and did not find any unguarded dependencies. I didn't check the separate adapters or breeze.labs.

**Comment by eXon** [comment]
I found a way to make it work but I had to make quite a few ugly hacks. Maybe it is because I am using it with webpack (it bundles my app for the client/server). 

- I had to alias breeze to breeze-client because it was using the wrong name
- I created an adaptor to use superagent instead of jquery (was pretty easy to do, not a big deal)
- I had to set breeze global and set Q manually:

```javascript
var breeze = require('breeze-client/build/breeze.base.debug');
var SuperAgentAdapter = require('./SuperAgentAdapter');

global.breeze = breeze;
breeze.config.setQ(require('q'));

require('breeze-client/build/adapters/breeze.dataService.webApi');
require('breeze-client/build/adapters/breeze.modelLibrary.backingStore');
require('breeze-client/build/adapters/breeze.uriBuilder.json');
require('./SuperAgentAdapter');

breeze.config.initializeAdapterInstance('modelLibrary', 'backingStore', true);
breeze.config.registerAdapter('ajax', SuperAgentAdapter);

module.exports = breeze;
```

I though at first it was very weird to plug something like that inside node.js. At least now it works but it could have been easier.

**Comment by mkaag** [comment]
Hi @eXon,

I am facing the very same issue, can you shed some light on your implementation in SuperAgentAdapter?

Thank you, regards,
Maurice

**Comment by wardbell** [comment]
I don't see an action item here.

**Comment by mkaag** [comment]
Hi @wardbell, indeed there is no action from your side. I simply can't use breeze.js as I want: query OData .NET server from NodeJS server, maybe you have something in your bag to remediate this use case?

**Comment by wardbell** [comment]
I'll point this issue to a pal who is running breeze on node. Maybe he has a clue.

**Comment by wardbell** [comment]
I checked. It's not a common scenario. Sounds like you have a workaround. Let us know if you can think of a better way.

**Comment by nojaf** [comment]
@mkaag, you can take a look at https://github.com/jdanyow/aurelia-breeze/blob/master/src/ajax-adapter.js

**Comment by rastographics** [comment]
@eXon would you be able to share your SuperAgentAdapter implementation?
